[package]
name = "clippy_dev"
version = "0.0.1"
authors = ["Philipp Hansch <dev@phansch.net>"]
edition = "2018"

[dependencies]
bytecount = "0.6"
clap = "2.33"
itertools = "0.8"
regex = "1"
lazy_static = "1.0"
shell-escape = "0.1"
walkdir = "2"
reqwest = { version = "0.10", features = ["blocking", "json"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
deny-warnings = []
issues = ["reqwest", "serde"]
