language: rust
rust: nightly
sudo: false

script:
 - python util/update_lints.py -c
 - cargo build --features debugging
 - rm -rf target/ Cargo.lock
 - cargo test --features debugging

 # only test regex_macros if it compiles
 - if [[ "$(cargo build --features 'debugging test-regex_macros')" = 101 ]]; then cargo test --features 'debugging test-regex_macros'; fi

# trigger rebuild of the clippy-service
after_success:
- |
    #!/bin/bash
    set -e
    if [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
       [ "$TRAVIS_REPO_SLUG" == "Manishearth/rust-clippy" ] &&
       [ "$TRAVIS_BRANCH" == "master" ] &&
       [ "$TRAVIS_TOKEN_CLIPPY_SERVICE" != "" ] ; then

       curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token $TRAVIS_TOKEN_CLIPPY_SERVICE" \
            -d "{ \"request\": { \"branch\":\"master\" }}" \
            https://api.travis-ci.org/repo/ligthyear%2Fclippy-service/requests

    else
      echo "Ignored"
    fi
