[package]
name = "clippy"
version = "0.0.6"
authors = [
	"Manish Goregaokar <manishsmail@gmail.com>",
	"Andre Bogus <bogusandre@gmail.com>"
]
description = "A bunch of helpful lints to avoid common pitfalls in Rust"
repository = "https://github.com/Manishearth/rust-clippy"
readme = "README.md"
license = "MPL-2.0"
keywords = ["clippy", "lint", "plugin"]

[lib]
name = "clippy"
plugin = true

[dev-dependencies]
compiletest_rs = "*"
regex = "*"
regex_macros = "*"
lazy_static = "*"

[features]

structured_logging = []