[crates]
# some of these are from cargotest
bevy = {name = "bevy", versions = ['0.10.1']}
deno = {name = "deno", versions = ['1.34.2']}

[recursive]
ignore = [
    # Takes ~30s to lint
    "combine",
    # Has 1.2 million `clippy::match_same_arms`s
    "unicode-normalization",
]
